version: "3.9"

services:
    db:
        image: postgres:16
        container_name: futurisys_db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: futurisys_db
        ports:
            - "5432:5432"
        volumes:
            - futurisys_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d futurisys_db"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 5s

    api:
        build: .
        container_name: futurisys_api
        command: bash -c "python create_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - .:/app

volumes:
    futurisys_data:
